name: map_api_demo
description: Demonstration of Flutter's map capabilities.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  map_api:
    path: ../
  flutter_map: ^0.14.0
  latlong2: ^0.8.1

dependency_overrides:
  flutter_map: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
