name: map_api
description: Demonstration of Flutter's map capabilities.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^0.11.0
  latlong: ^0.6.1
  flutter_map_marker_cluster: any
  user_location: any
  flutter_map_tappable_polyline: any
  lat_lon_grid_plugin: any
  flutter_map_marker_popup: any
  map_elevation: any
  http: any

dependency_overrides:
  flutter_map: 0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
