name: map_api
description: Demonstration of Flutter's map capabilities.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^0.13.1
  latlong2: ^0.8.0
  flutter_map_location: ^0.12.0
  http: ^0.13.3

dependency_overrides:
  logging: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  dartdoc: ^0.45.0

flutter:
  uses-material-design: true
